[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.6.1"
itertools = "0.14.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = 'abort'
strip = true
